app/__init__.py
from flask import Flask, render_template
from .config import config_by_name
from .routes.main_routes import main
from .routes.api_routes import api

import os
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def create_app(config_name=None):
    app = Flask(__name__, instance_relative_config=True)
    config_name = config_name or os.getenv('FLASK_ENV') or 'development'
    app_config = config_by_name.get(config_name, config_by_name['development'])
    app.config.from_object(app_config)
    app.config.from_pyfile('config.py', silent=True)
    app.register_blueprint(main)
    app.register_blueprint(api)
    register_error_handlers(app)
    return app

def register_error_handlers(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def internal_server_error(e):
        return render_template('errors/500.html'), 500

app/routes/api_routes.py
from flask import Blueprint, jsonify, request
import os
import logging
from app.utils.utils import addnote as add_anki_note
from app.utils.utils import addnote_english as add_anki_note_english
from app.utils.container import handle_container

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

api = Blueprint('api', __name__, url_prefix='/api')

@api.route("/addnote", methods=["POST"])
def addnote():
  HANDLE_CONTAINER = os.environ.get('HANDLE_CONTAINER', 'False').lower() == 'true'
  ankiConnect = os.environ.get("ANKICONNECT_URL")
  if not ankiConnect:
    return jsonify({"error": "ANKICONNECT_URL environment variable not set"}), 500

  data = request.get_json()
  if not data:
        return jsonify({"error": "Missing JSON data"}), 400
  word = data.get("word").strip()
  dropdown_value = data.get("dropdownValue")

  if not word:
    return jsonify({"message": "Missing 'word'"}), 400

  try:
    if HANDLE_CONTAINER:
      handle_container()
    deck = dropdown_value.capitalize()
    if dropdown_value == "japanese":
      add_anki_note(ankiConnect, deck, word)
      return jsonify({
            "message": "Note added successfully",
            "word": word,
            "value": dropdown_value
      }), 200
    else:
      add_anki_note_english(ankiConnect, deck, word)
      return jsonify({
            "message": "Note added successfully",
            "word": word,
            "value": dropdown_value
      }), 200
  except Exception as e:
    return jsonify({"error": str(e)}), 500

app/routes/main_routes.py
from flask import Blueprint, render_template
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('home.html')

app/templates/home.html
{% extends "layouts/base.html" %}

{% block title %}Anki Add{% endblock %}

{% block content %}
<form id="language">
    <input type="text" id="word" name="word" autocomplete="off" placeholder="Enter word" required
        value="{{ word or '' }}">
    <div class="languages" tabindex="0">
        <div class="selected" data-value="japanese">Japanese</div>
        <ul class="options">
            <li data-value="japanese">Japanese</li>
            <li data-value="english">English</li>
        </ul>
    </div>
    <input type="hidden" name="dropdownValue" id="dropdownValue" value="japanese">
    <button type="submit">Add</button>
</form>

<div id="result"></div>
{% endblock %}

app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Anki Add{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

    <div class="container">
        <a href="{{ url_for('main.home') }}">
            <h1>📝🈯️ Anki Add</h1>
        </a>
        {% block content %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>

</html>